/// <reference types="cypress"/>
// Accessing the GUI elements
it("GUI Elements",function()
{

    cy.visit("https://ssc.nic.in/")
    cy.get('#signUpLink').click()
    cy.get('#rbAadharYes').check()
    cy.get('#AadharNumber').type('906123931529')
    cy.get('#VerifyAadharNumber').type('906123931529')
    cy.get('#Name').type('Akshita katna')
    cy.get('#VerifyName').type('Akshita katna')
    cy.get('#rbHaveEverChangedNameNo').check()
    cy.get('#FatherName').type('Akbar katna')
    cy.get('#VerifyFatherName').type('Akbar katna')
    cy.get('#MotherName').type('Kesri katna')
    cy.get('#VerifyMotherName').type('Kesri katna')
    cy.get('#DateOfBirth').type('30/12/1993{enter}')
    cy.get('#VerifyDateOfBirth').type('30/12/1993{enter}')
    cy.get('select').eq(1).select('14')
    cy.get('select').eq(2).select('14')
    cy.get('#SecondaryRollNum').type('586210')
    cy.get('#VerifySecondaryRollNum').type('586210')
    cy.get('select').eq(3).select('2009')
    cy.get('select').eq(4).select('2009')
    cy.get('#rbFeMale').check()
    cy.get('#rbVerifyFeMale').check()
    cy.get('select').eq(5).select('4')
    cy.get('#MobileNum').type('9805408154')
    cy.get('#VerifyMobileNum').type('9805408154')
    cy.get('#EmailID').type('dikshakana912@gmail.com')
    cy.get('#VerifyEmailID').type('dikshakana912@gmail.com')
    cy.get('select').eq(6).select('6') 
})